name: CI
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v2
      with:
        fetch-depth: '2'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        pip install coverage
        coverage run -m unittest discover tests -v
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
    - name: Wemake Python Stylguide
      uses: wemake-services/wemake-python-styleguide@0.13.4
      continue-on-error: true
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}